apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: "arn:aws:iam::740705561466:role/EC2_admin"  
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: dushims/fastapi-news
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 400m
