apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1  # You can adjust the number of replicas
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: dushims/fastapi-news
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 400m
